[[NVTX]]
arch = "aarch64"
git-tree-sha1 = "c38bbe58385bee4e0a440b5d8306a8f0893344f1"
libc = "glibc"
os = "linux"

    [[NVTX.download]]
    sha256 = "37ade446b518e73c35c5ff2182f29ab8ab64c8ef5502006826f1d43a3af3292c"
    url = "https://github.com/JuliaBinaryWrappers/NVTX_jll.jl/releases/download/NVTX-v3.1.0+2/NVTX.v3.1.0.aarch64-linux-gnu.tar.gz"
[[NVTX]]
arch = "powerpc64le"
git-tree-sha1 = "27620aa94b6e65681db7cf4a69123fe74c26b610"
libc = "glibc"
os = "linux"

    [[NVTX.download]]
    sha256 = "a3bdd103429856da68b7b75f3fe4d51855fcf4d179813c8217ed37683e7d17bb"
    url = "https://github.com/JuliaBinaryWrappers/NVTX_jll.jl/releases/download/NVTX-v3.1.0+2/NVTX.v3.1.0.powerpc64le-linux-gnu.tar.gz"
[[NVTX]]
arch = "x86_64"
git-tree-sha1 = "0b6483311b60bc85d320f64bb66fd2e310916fb1"
libc = "glibc"
os = "linux"

    [[NVTX.download]]
    sha256 = "041f6c02314c1ad9bd8f054e3355c652e8ae6492f384659c31e7f7a0be7e5f66"
    url = "https://github.com/JuliaBinaryWrappers/NVTX_jll.jl/releases/download/NVTX-v3.1.0+2/NVTX.v3.1.0.x86_64-linux-gnu.tar.gz"
[[NVTX]]
arch = "x86_64"
git-tree-sha1 = "b4eeaf094ffb6aacf1b20ee5d2ac9aa1818fc732"
os = "windows"

    [[NVTX.download]]
    sha256 = "7b85facbc4771673600ebd9d343e7aaf8b9a6c68e0b27b3e820cd3067f6c1076"
    url = "https://github.com/JuliaBinaryWrappers/NVTX_jll.jl/releases/download/NVTX-v3.1.0+2/NVTX.v3.1.0.x86_64-w64-mingw32.tar.gz"
