[[NVTX]]
arch = "aarch64"
git-tree-sha1 = "a6caecd02e5de6708ee179a66088f26a5f69e053"
libc = "glibc"
os = "linux"

    [[NVTX.download]]
    sha256 = "606d860e78649ae0a4605c75cb5a578b7bcc3aca64638569d9666a007a05d00b"
    url = "https://github.com/JuliaBinaryWrappers/NVTX_jll.jl/releases/download/NVTX-v3.1.1+0/NVTX.v3.1.1.aarch64-linux-gnu.tar.gz"
[[NVTX]]
arch = "powerpc64le"
git-tree-sha1 = "3a93885d9e491cbd54b6006765742c0baae08176"
libc = "glibc"
os = "linux"

    [[NVTX.download]]
    sha256 = "adac94da29847fca954b3c41e796d7613dff6258fa4faf9023ffa01777be5e43"
    url = "https://github.com/JuliaBinaryWrappers/NVTX_jll.jl/releases/download/NVTX-v3.1.1+0/NVTX.v3.1.1.powerpc64le-linux-gnu.tar.gz"
[[NVTX]]
arch = "x86_64"
git-tree-sha1 = "abb37beb7ab272d9cb3c0eafbe47091f874b94f0"
libc = "glibc"
os = "linux"

    [[NVTX.download]]
    sha256 = "c16ba0b0995231d93a4ff69921d9512158ecd83ed26fe630a539efb2a27c3981"
    url = "https://github.com/JuliaBinaryWrappers/NVTX_jll.jl/releases/download/NVTX-v3.1.1+0/NVTX.v3.1.1.x86_64-linux-gnu.tar.gz"
[[NVTX]]
arch = "x86_64"
git-tree-sha1 = "7bfcddd356bce236865de64f75134c469eaf2571"
os = "windows"

    [[NVTX.download]]
    sha256 = "f9688cb70b319ccb1e42ebe10b20ae9e44694e012b093461f060aad507d4d0c3"
    url = "https://github.com/JuliaBinaryWrappers/NVTX_jll.jl/releases/download/NVTX-v3.1.1+0/NVTX.v3.1.1.x86_64-w64-mingw32.tar.gz"
